CREATE PROC FI_SP_IncBeneficiario
    @IDCLIENTE INT,
    @CPF       VARCHAR(11),
    @NOME      VARCHAR(50)
AS
BEGIN
    INSERT INTO BENEFICIARIOS (IDCLIENTE, CPF, NOME)
    VALUES (@IDCLIENTE, @CPF, @NOME)

    SELECT SCOPE_IDENTITY() AS ID
END